name: DuffiaPlugin
main: com.Mc_Duff.DuffiaPlugin.DuffiaPlugin
version: 0.4

commands:
   spawn:
      description: Teleport self to spawn.
      usage:
           /<command>
   pvp:
      description: Check own PVP stats.
      usage:
           /<command>
   buy:
      description: Spend PVP points.
      usage:
           /<command> [args]
   money:
      description: economy acount info
      usage:
           /<command> [args]
   pay:
      description: economy  pay another player
      usage:
           /<command> [args]
   addmoney:
      description: economy add money to account (op only)
      usage:
           /<command> [args]
   removemoney:
      description: economy remove money from account (op only)
      usage:
           /<command> [args]
   startpack:
      description: basic starter kit
      usage:
           /<command>