name: DuffiaPlugin
main: com.Mc_Duff.DuffiaPlugin.DuffiaPlugin
version: 0.3
authors: [Mc_Duff]

commands:
   spawn:
      description: Teleport self to spawn.
      usage:
           /<command>
   pvp:
      description: Check own PVP stats.
      usage:
           /<command>
   buy:
      description: Spend PVP points.
      usage:
           /<command> [args]